---
- name: victoria-metrics.vmsingle
  src: https://github.com/devops-automations/ansible-role-victoria-metrics.vmsingle
  version: main
  scm: git

- name: nginx
  src: https://github.com/nginx/ansible-role-nginx
  version: main
  scm: git

- name: nginx-config
  src: https://github.com/nginx/ansible-role-nginx-config.git
  version: main
  scm: git